[New LWP 27911]
Core was generated by `'.
Program terminated with signal SIGABRT, Aborted.
#0  0x0000000005387cc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#0  0x0000000005387cc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x000000000538b0d8 in __GI_abort () at abort.c:89
#2  0x0000000004e97535 in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x0000000004e956d6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x0000000004e95703 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x0000000004e95922 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x0000000004ee7447 in std::__throw_out_of_range(char const*) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00000000004011bf in std::vector<double, std::allocator<double> >::_M_range_check (this=0xfff000920, __n=5) at /usr/include/c++/4.8/bits/stl_vector.h:794
#8  0x0000000000400f11 in std::vector<double, std::allocator<double> >::at (this=0xfff000920, __n=5) at /usr/include/c++/4.8/bits/stl_vector.h:812
#9  0x0000000000400b38 in TestPerioda (v=std::vector of length 5, capacity 5 = {...}, p=3) at /rhome/s/sdziho1/workspace/TP/T2/Z2/main.cpp:10
#10 0x0000000000400c92 in main () at /rhome/s/sdziho1/workspace/TP/T2/Z2/main.cpp:37
